server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/travel_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: yourpassword
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: mock
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
orchestrator:
  service:
    url: VLA